
name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: rkpyap-dyna1 
  AZURE_RESOURCE_GROUP: DefaultResourceGroup-EUS  # set this to the name of your Azure Web App
  PYTHON_VERSION: '3.11'              # set this to the Python version to use

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  id-token: write  # 🔹 Needed for OIDC authentication
  contents: read   # 🔹 Needed to access repo files

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

#https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-secret
      - name: Login to Azure  
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE}}


